### ISSUE TITLE
Loading images from directory rather than gravatar

### ISSUE THREAD

**Issue by synpredator** [HubSpot/facewall#16]
Hi, I was wondering, Is it possible to load images from a local directory where the files are hosted rather than using the website gravatar? and if so, How do i go about this? Lets say I want the images to be pulled based on the user ID? and the images are in /images/?

Is it possible?

**Comment by adamschwartz** [comment]
Absolutely.

If you modify [avatarInGridSize ->](https://github.com/HubSpot/facewall/blob/d684f076a395cf52bd45d0e63cdadc91bb1d4f25/app/views/facewall.coffee#L383-L384) to simply return `url`, manually set the `gravatar` property in your employee JSON to be the local `/images/USER_ID.jpg` paths, and remove [this line](https://github.com/HubSpot/facewall/blob/d684f076a395cf52bd45d0e63cdadc91bb1d4f25/app/collections/employees.coffee#L320) from the employees JSON parsing, you should be all set.

**Comment by synpredator** [comment]
Hi Adam

Thank you for responding, I am unsure how to edit the return url or what to set it too, Also everytime I try and add employees to a jason file it errors, is there an example of the employees json file anywhere?
